# Private bucket that stores all user-uploaded files. Public access is
# blocked entirely — the application reaches objects only through
# short-lived pre-signed URLs generated by the backend.
resource "aws_s3_bucket" "file_storage" {
  bucket = var.bucket_name

  tags = {
    Project     = "cloud-file-storage"
    Environment = var.environment
  }
}

resource "aws_s3_bucket_public_access_block" "file_storage" {
  bucket = aws_s3_bucket.file_storage.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Versioning is what powers the app's file-versioning feature: every
# re-upload to the same key becomes retrievable/restorable history instead
# of overwriting data.
resource "aws_s3_bucket_versioning" "file_storage" {
  bucket = aws_s3_bucket.file_storage.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "file_storage" {
  bucket = aws_s3_bucket.file_storage.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Pre-signed PUT/GET requests originate from the browser, so CORS must
# allow the frontend origin.
resource "aws_s3_bucket_cors_configuration" "file_storage" {
  bucket = aws_s3_bucket.file_storage.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "PUT", "POST", "DELETE", "HEAD"]
    allowed_origins = [var.allowed_cors_origin]
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}

# Old, superseded (non-current) object versions are moved to cheaper
# storage after 30 days and expired after a year, so version history does
# not grow the storage bill unbounded.
resource "aws_s3_bucket_lifecycle_configuration" "file_storage" {
  bucket = aws_s3_bucket.file_storage.id

  rule {
    id     = "manage-noncurrent-versions"
    status = "Enabled"

    noncurrent_version_transition {
      noncurrent_days = 30
      storage_class   = "STANDARD_IA"
    }

    noncurrent_version_expiration {
      noncurrent_days = 365
    }
  }
}
